export FG_BLACK=$(tput setaf 0)
export FG_BLACK_LIGHT=$(tput setaf 8)
export FG_RED=$(tput setaf 1)
export FG_RED_LIGHT=$(tput setaf 9)
export FG_GREEN=$(tput setaf 2)
export FG_GREEN_LIGHT=$(tput setaf 10)
export FG_YELLOW=$(tput setaf 3)
export FG_YELLOW_LIGHT=$(tput setaf 11)
export FG_BLUE=$(tput setaf 4)
export FG_BLUE_LIGHT=$(tput setaf 12)
export FG_MAGENTA=$(tput setaf 5)
export FG_MAGENTA_LIGHT=$(tput setaf 13)
export FG_CYAN=$(tput setaf 6)
export FG_CYAN_LIGHT=$(tput setaf 14)
export FG_WHITE=$(tput setaf 7)
export FG_WHITE_LIGHT=$(tput setaf 15)

export BG_BLACK=$(tput setab 0)
export BG_BLACK_LIGHT=$(tput setab 8)
export BG_RED=$(tput setab 1)
export BG_RED_LIGHT=$(tput setab 9)
export BG_GREEN=$(tput setab 2)
export BG_GREEN_LIGHT=$(tput setab 10)
export BG_YELLOW=$(tput setab 3)
export BG_YELLOW_LIGHT=$(tput setab 11)
export BG_BLUE=$(tput setab 4)
export BG_BLUE_LIGHT=$(tput setab 12)
export BG_MAGENTA=$(tput setab 5)
export BG_MAGENTA_LIGHT=$(tput setab 13)
export BG_CYAN=$(tput setab 6)
export BG_CYAN_LIGHT=$(tput setab 14)
export BG_WHITE=$(tput setab 7)
export BG_WHITE_LIGHT=$(tput setab 15)

export BOLD=$(tput bold)                # Start bold text
export UNDERLINED=$(tput smul)          # Start underlined text
export UNDERLINED_OFF=$(tput rmul)      # End underlined text
export REVERSE=$(tput rev)              # Start reverse video
export BLINK=$(tput blink)              # Start blinking text
export INSISIBLE=$(tput invis)          # Start invisible text
export STANDOUT=$(tput smso)            # Start "standout" mode
export STANDOUT_OFF=$(tput rmso)        # End "standout" mode
export RESET_ALL=$(tput sgr0)           # Turn off all attributes

